### ISSUE TITLE
better support for the "pendrive" use case

### ISSUE THREAD

**Issue by mvdan** [ipfs-shipyard/go-ipfs-desktop#7]
That is, a use case where someone runs IPFS from a pendrive, without installing it on the system.

Right now we look for `ipfs` in $PATH. We should also look for it somewhere local; for example, right next to where the go-ipfs-desktop binary is.

**Comment by lidel** [comment]
I'd go with lookup order:
- the same directory as go-ipfs-desktop binary (`realpath go-ipfs-desktop`)
  - this will often be different  from the current directory (`pwd`)
- `$PATH`
